--- 
- hosts: local 
  name: Installing monitoring server 
  tasks: 
    - include: prerequisites.yml 
    - include: node_exporter_install.yml 
    - include: node_exporter_service_install.yml 
    - include: sensors_install.yml 
    - include: cadvisor_install.yml 
    - include: blackbox_exporter_install.yml
    - include: prometheus_install.yml 
    - include: grafana_install.yml 

- hosts: distant 
  name: Installing Distant Exporter 
  tasks: 
    - include: prerequisites.yml 
    - include: node_exporter_install.yml 
    - include: node_exporter_service_install.yml 
    - include: sensors_install.yml 
    - include: cadvisor_install.yml 
