---
- name: Downloading Prometheus docker image
  become: true
  docker_image:
    name: quay.io/prometheus/prometheus:v1.8.0
    state: present

- name: Create Share Folder 1/2
  become: true
  file:
    path: /home/docker_share/prometheus
    mode: 0755
    state: directory

- name: Create Share Folder 2/2
  become: true
  file:
    path: /home/docker_share/data/prometheus
    mode: 0755
    state: directory

- name: Copie conf file for Prometheus
  become: true
  template:
    src: conf/prometheus/prometheus.yml
    dest: /home/docker_share/prometheus/prometheus.yml
    mode: 0644

- name: Start Prometheus Container
  become: true
  docker_container:
    name: prometheus
    image: quay.io/prometheus/prometheus:v1.8.0
    volumes: 
      - "/home/docker_share/prometheus/:/etc/prometheus/:rw"
      - "/home/docker_share/data/prometheus/:/prometheus/:rw"
    restart_policy: unless-stopped
    published_ports: 9090:9090
    state: started
