global:
 scrape_interval: 15s

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets: ['localhost:9090']

 - job_name: node
   metrics_path: /metrics
   static_configs:
    - targets: ['IpHost:9100','IpNode1:9100',...]
 
 - job_name: service
   metrics_path: /metrics
   static_configs:
    - targets: ['172.17.0.1:9110','IpNode1:9110',...]

 - job_name: cadvisor
   static_configs:
     - targets: ['172.17.0.1:8090','IpNode1:8090',...]

